### ISSUE TITLE
Hello， do you know about SCM（i. e. sequential compounding method）

### ISSUE THREAD

**Issue by Fatigerrr** [rcsalomao/FORM#1]
Hello， do you know about SCM（i. e. sequential compounding method)
 thanks for you reply :)

**Comment by rcsalomao** [comment]
Hello!
Up til now I haven't heard of SCM.
I have acessed the work "Evaluation of multivariate normal integrals for general systems by sequential compounding" from Kang and Song (2010) and as far as I can grasp, it is a method to compute system reliabilities (serial, parallel and/or general) correct?
The only way I knew to be able to compute general systems with FORM was through the Matrix-based method (MSR), but to be honest, I couldn't really understand the implementation details. So I left it for a later time maybe.
This SCM seems to be really interesting as well (and more approachable perhaps).
Thanks for reaching out!

**Comment by Fatigerrr** [comment]
> Hello! Up til now I haven't heard of SCM. I have acessed the work "Evaluation of multivariate normal integrals for general systems by sequential compounding" from Kang and Song (2010) and as far as I can grasp, it is a method to compute system reliabilities (serial, parallel and/or general) correct? The only way I knew to be able to compute general systems with FORM was through the Matrix-based method (MSR), but to be honest, I couldn't really understand the implementation details. So I left it for a later time maybe. This SCM seems to be really interesting as well (and more approachable perhaps). Thanks for reaching out!

Yes，I think SCM is more convenient than B， if you want to know more about MSR, you can cheak this github repository
STructural Reliability Anaylsis using Python (STRAP) 
https://github.com/99taeha/STRAP#structural-reliability-anaylsis-using-python-strap
It may helps 
oh， I can not find your LinkedIn count

**Comment by rcsalomao** [comment]
For some reason Linkedin didn't setup the public profile. Now it should be working.
Thanks for the info!

**Comment by rcsalomao** [comment]
Just merged commit a66c45c22cab1f26190181a38f4753d655944c3e with the implementation of the SCM for 'parallel', 'serial' and general systems.
As such, I will be closing this issue but if any bug happens or the system feature presents some wrong behaviour please feel free to comment here or open another issue.

I am really grateful for the information and reaching out!
Thanks a lot!!
